/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001a41",
        "on-secondary-fixed": "#031b3e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary-container": "#ffc5ac",
        "surface-container-high": "#e6e8eb",
        "tertiary-fixed": "#ffdbcc",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f7",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e6",
        "primary-fixed-dim": "#adc7ff",
        "inverse-primary": "#adc7ff",
        "background": "#f7f9fc",
        "on-secondary-fixed-variant": "#34476c",
        "tertiary": "#752b00",
        "surface-tint": "#0d5bbc",
        "primary-fixed": "#d8e2ff",
        "error": "#ba1a1a",
        "tertiary-container": "#9b3c00",
        "outline": "#727784",
        "surface": "#f7f9fc",
        "surface-container": "#eceef1",
        "on-secondary-container": "#475a80",
        "on-tertiary-fixed-variant": "#7c2e00",
        "secondary-container": "#bed2fe",
        "on-surface": "#191c1e",
        "on-primary-fixed-variant": "#004493",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e6",
        "primary": "#00408b",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fc",
        "on-surface-variant": "#424752",
        "on-secondary": "#ffffff",
        "secondary": "#4b5e85",
        "inverse-on-surface": "#eff1f4",
        "on-background": "#191c1e",
        "outline-variant": "#c2c6d4",
        "surface-dim": "#d8dadd",
        "on-tertiary-fixed": "#351000",
        "on-primary-container": "#bfd2ff",
        "primary-container": "#0057b8",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b3c7f3",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
    extend: {},
  },
  plugins: [],
}